spring.application.name=banking-user-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_user_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info