spring.application.name=banking-account-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_account_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info